weights: yolov5x.pt
cfg: ''
data: 3objs.yaml
hyp: ../../../yolov5/data/hyps/hyp.scratch-low.yaml
epochs: 200
batch_size: 1
imgsz: 256
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: /home/alexandre/asd-research/nn/3objs
name: runs/train/full1
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: /home/alexandre/asd-research/nn/3objs/runs/train/full1
